version: '3.9'

services:

  db:
    image: postgres
    container_name: "user"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: "user-db"
    ports:
      - "5432:5432"